### ISSUE TITLE
product_fifo_lifo behaviours

### ISSUE THREAD

**Issue by mwithi** [alephobjects/ao-openerp#1]
As suggested by Claudio from LulzBot.com I report here my questions:

I'm writing you beacuse I'm trying the module 'product_fifo_lifo'

I'd like to know:
- the module makes stock_valuation required: may a keep "Periodic (manual)"
- what happen if the module is installed in a production environment with already existing warehouse movements?
- what happen if I switch from cost_method "Standard Price" to "FIFO" and viceversa several times while using the system?
- after installing the module it seems to erase all costs and stock_valuations field for my product, is it possible to avoid this?

Thanks in advance,
Alessandro.

**Comment by mwithi** [comment]
during the product_fifo_lifo module installation I got this messages:
```
openerp.osv.orm: column standard_price (Cost) in table product_template removed: converted to a function !
openerp.osv.orm.schema: Table 'product_template': dropped column 'standard_price' with cascade
openerp.osv.orm: column cost_method (Costing Method) in table product_template removed: converted to a function !
openerp.osv.orm.schema: Table 'product_template': dropped column 'cost_method' with cascade
openerp.osv.orm.schema: Table 'product_product': column 'valuation': dropped NOT NULL constraint
openerp.osv.orm: column valuation (Inventory Valuation) in table product_product removed: converted to a function !
openerp.osv.orm.schema: Table 'product_product': dropped column 'valuation' with cascade
```

Now, in production environment the log shows:
```
column valuation is in the table product_product but not in the corresponding object product.product
```

And actually I'm not able to create any new product and any models inherited from product.product, it shows this error:
```
ValidateError
The value "product.product,1285" for the field "ir_property.res_id" is not in the selection
```

The fields are there in the DB table, I can import values via CSV, but the create function within OpenERP just fails...

Please help!!

**Comment by mwithi** [comment]
Maybe I've found the problem. The original fields
- standard_price (fields.float)
- cost_method (fields.selection)
- valuation (fields.selection)

are re-defined as fields.property() in product.py file. Why you did it? Is there any reason to ask fields.property behaviour on those fields?

**Now I patched my code in order to redefine those fields and keeping the original types.**

I've tried to launch test-suite with command (--log-level=test -i product_fifo_lifo --test-enable) but it fails also on the original code, so I don't think is a reliable test.

**Comment by b-kannan** [comment]
This error will go away if you upgrade the database with 
product_fifo_lifo module again. Please try this.

Balaji Kannan

**Comment by b-kannan** [comment]
The module was developed by Odoo Development Team and not us. Yes, you 
are right. The original fields were converted to property fields in this 
module.

Balaji

**Comment by mwithi** [comment]
Upgrading the module doesn't fix. The only solution seems redefine those fields as actual fields and not properties
